name = "chasqui-productionv3"
compatibility_date = "2025-10-23"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
# opcional si tienes API en el worker:
# run_worker_first = ["/api/*"]
